name: noticesinfo
description: A new Flutter project.
# The following line prevents the package from being accidentally published to
# pub.dev using `flutter pub publish`. This is preferred for private packages.
publish_to: 'none' # Remove this line if you wish to publish to pub.dev

# The following defines the version and build number for your application.
# A version number is three numbers separated by dots, like 1.2.43
# followed by an optional build number separated by a +.
# Both the version and the builder number may be overridden in flutter
# build by specifying --build-name and --build-number, respectively.
# In Android, build-name is used as versionName while build-number used as versionCode.
# Read more about Android versioning at https://developer.android.com/studio/publish/versioning
# In iOS, build-name is used as CFBundleShortVersionString while build-number is used as CFBundleVersion.
# Read more about iOS versioning at
# https://developer.apple.com/library/archive/documentation/General/Reference/InfoPlistKeyReference/Articles/CoreFoundationKeys.html
# In Windows, build-name is used as the item product name, while build-number is used as
# the item product version.
version: 1.0.8+9

environment:
  sdk: '>=3.2.6 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  flutter_localizations: # Add this line
    sdk: flutter         # Add this line
  intl: ^0.20.2           # Add this line
  
  google_fonts: ^6.1.0
  carousel_slider: ^5.1.1 # Updated to latest version as per user feedback
  firebase_core: ^4.3.0
  firebase_auth: ^6.1.3
  google_sign_in: ^6.2.2
  sign_in_button: ^4.0.1


  # The following adds the Cupertino Icons font to your application.
  # Use with the CupertinoIcons class for iOS style icons.
  cupertino_icons: ^1.0.2
  flutter_html: ^3.0.0-beta.2
  http: ^1.1.0
  url_launcher: ^6.2.2
  shared_preferences: ^2.2.2
  image_picker: ^1.2.0
  google_maps_flutter: ^2.5.0
  geocoding: ^2.2.1
  flutter_typeahead: ^5.2.0
  flutter_keyboard_visibility: ^6.0.0
  smooth_page_indicator: ^1.1.0
  share_plus: ^7.0.2
  geolocator: ^11.0.0
  intl_phone_field: ^3.2.0
  package_info_plus: ^8.0.0
  flutter_secure_storage: ^9.0.0
  google_cloud_translation: ^0.0.4 # Downgraded as per suggestion
  provider: ^6.1.1 # Add provider package

dev_dependencies:
  flutter_test:
    sdk: flutter

  # The "flutter_lints" package adds a set of recommended lints to the app to
  # encourage good coding practices. The lint set provided by the package is
  # activated in the `analysis_options.yaml` file located at the root of your
  # package. See that file for information about deactivating specific lint
  # rules and activating additional ones.
  flutter_lints: ^2.0.0

# For information on the generic Dart part of this file, see the
# following page: https://dart.dev/tools/pub/pubspec

# The following section is specific to Flutter packages.
flutter:
  generate: true
  uses-material-design: true
  # Add this section for localization
  # The following line ensures that the Material Icons font is
  # included with your application, so that you can use the icons in
  # the material Icons class.

  # To add assets to your application, add an assets section, like this:
  assets:
    - assets/image/

  # An image asset can refer to one or more resolution-specific "variants", see
  # https://flutter.dev/assets-and-images/#resolution-aware

  # For details regarding adding assets from package dependencies, see
  # https://flutter.dev/assets-and-images/#from-packages

  # To add custom fonts to your application, add a fonts section here,
  # in this "flutter" section. Each entry in this list should have a
  # "family" key with the font family name, and a "fonts" key with a
  # list giving every asset and other descriptors for the font. For
  # example:
  # fonts:
  #   - family: Schyler
  #     fonts:
  #       - asset: fonts/Schyler-Regular.ttf
  #       - asset: fonts/Schyler-Italic.ttf
  #         style: italic
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700
  #
  # For details regarding fonts in packages, see
  # https://flutter.dev/custom-fonts/#from-packages
